### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by dondiego4697** [autovance/ftp-srv#201] opened 2020-05-25 08:33 UTC
`Unhandled rejection Error: Cannot find module '../registry' from 'node_modules/ftp-srv/src/commands/registration/feat.js'`

If I run code with ts-builded code, circular dependencies was created.

If I run via CLI everything is okay, which means that it does not work with TS

`registration.js` already required `feat.js` but `feat.js` require `registration.js`

https://github.com/trs/ftp-srv/blob/master/src/commands/registry.js#L10
https://github.com/trs/ftp-srv/blob/master/src/commands/registry.js#L10

**Comment by trs** [comment] 2020-07-20 21:11
Interesting, circular dependencies should be a non-issue with node. I guess typescript has an issue resolving these.

This probably caused by the `require` occurring within the function call. I'll try moving it to the top level and see if that resolves this. https://github.com/autovance/ftp-srv/pull/208

**Comment by forstermatth** [comment] 2020-08-25 17:49
If this is still an issue, please reopen!

**Closed by forstermatth** 2020-08-25 17:49 UTC
Labels: bug
